# Generated by Django 5.2.9 on 2025-12-17 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('layout', models.TextField(default='11111\n11111', help_text='用1代表座位，0代表过道，换行代表下一行', verbose_name='布局图(1座0空)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='密码')),
                ('status', models.CharField(choices=[('normal', '正常'), ('blacklist', '黑名单'), ('whitelist', '白名单')], default='normal', max_length=10)),
                ('role', models.CharField(choices=[('user', '普通学生'), ('manager', '负责人/VIP')], default='user', max_length=10, verbose_name='角色')),
                ('violation_count', models.IntegerField(default=0)),
                ('is_auto_created', models.BooleanField(default=False, verbose_name='自动创建')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('seat_row', models.IntegerField()),
                ('seat_col', models.IntegerField()),
                ('date', models.DateField()),
                ('time_slot', models.IntegerField(choices=[(1, '08:00 - 10:00'), (2, '10:00 - 12:00'), (3, '14:00 - 16:00'), (4, '16:00 - 18:00'), (5, '19:00 - 22:00')], verbose_name='时间段')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin_action', models.BooleanField(default=False, verbose_name='管理员操作')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '申请中'), ('approved', '通过'), ('rejected', '拒绝')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.CharField(blank=True, default='', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
