# Generated by Django 5.2.9 on 2025-12-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.IntegerField(choices=[(1, '08:00 - 10:00'), (2, '10:00 - 12:00'), (3, '14:00 - 16:00'), (4, '16:00 - 18:00'), (5, '19:00 - 22:00')], verbose_name='时间段')),
                ('code', models.CharField(max_length=10, verbose_name='门禁密码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False, verbose_name='已通知')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
                'unique_together': {('classroom', 'date', 'time_slot')},
            },
        ),
    ]
