# Generated by Django 5.2.9 on 2025-12-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_seats_info',
            field=models.TextField(blank=True, default='', verbose_name='取消座位信息'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '08:00 - 10:00'), (2, '10:00 - 12:00'), (3, '14:00 - 16:00'), (4, '16:00 - 18:00'), (5, '21:15 - 22:00')], verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '08:00 - 10:00'), (2, '10:00 - 12:00'), (3, '14:00 - 16:00'), (4, '16:00 - 18:00'), (5, '21:15 - 22:00')], verbose_name='时间段'),
        ),
    ]
