"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vlbkyup_nx1gupc%d4tb+ywwuns4p7jtgq8^kfx(3z=9gfx8k2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans' # 中文

TIME_ZONE = 'Asia/Shanghai' # 时区

USE_I18N = True

USE_TZ = False # 简单起见，开发环境关闭时区感知，直接用本地时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- 自定义配置 ---
# 邮件后端：开发时在控制台打印邮件内容
# 使用自定义后端以在不同平台上以可读方式显示非 ASCII 文本（如中文）
EMAIL_BACKEND = 'core.mail_backends.DecodedConsoleBackend'
# 管理员接收通知邮箱
ADMIN_EMAIL = 'admin@hust.edu.cn'
# 网站域名 (用于生成链接)
SITE_DOMAIN = 'http://127.0.0.1:5678'

# 预约/申请相关可配置项（开发时使用）
# 超时未审核自动过期阈值（小时）
RESERVATION_TIMEOUT_HOURS = 24
# 预约日期过期阈值（天）：例如 1 表示当天过后第二天即视为过期
RESERVATION_EXPIRE_DAYS = 1
# 用户可预约的最大天数范围（默认 2 天）
RESERVATION_MAX_DAYS_AHEAD = 2
# 为负责人单独配置可预约的最大天数范围（默认 7 天）
RESERVATION_MAX_DAYS_AHEAD_MANAGER = 7
# cleanup 调度器间隔（分钟），cleanup_scheduler 将以此为周期执行清理任务
RESERVATION_CLEANUP_INTERVAL_MINUTES = 30
# 预约/取消截止时间（分钟）：必须在时间段开始前 N 分钟之前完成预约或取消操作
RESERVATION_BOOKING_WINDOW_MINUTES = 30
# 门禁密码通知提前时间（分钟）：在时间段开始前 N 分钟发送门禁密码
ACCESS_CODE_NOTIFY_MINUTES = 15
# 固定门禁密码（可选）：如果设置了此值，则使用固定密码；否则每次随机生成6位数字密码
ACCESS_CODE_FIXED = '123456'
# ACCESS_CODE_FIXED = None  # 设置为 None 或注释掉则使用随机密码
# 控制“申请升级”相关的界面元素：
#  - PROMOTION_ENABLE_10CLICK: 是否启用用户名上连续点击触发的隐藏申请入口（十次点击触发）
#  - PROMOTION_SHOW_BUTTON: 是否在页面右侧显示显式的「申请升级」按钮
PROMOTION_ENABLE_10CLICK = True
PROMOTION_SHOW_BUTTON = False

# --- 时间段配置 ---
# 定义可预约的时间段，格式为 (ID, '开始时间 - 结束时间')
TIME_SLOTS = (
    (1, '08:00 - 10:00'),
    (2, '10:00 - 12:00'),
    (3, '14:00 - 16:00'),
    (4, '16:00 - 18:00'),
    (5, '19:00 - 22:00'),
)
